# -*- coding: utf-8 -*-
"""1.0- Handling Missing values.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1X6VwUfDIJzgHeTPYUfy1tf8KB9YhIqJj

## Missing Values
Missing values occurs in dataset when some of the informations is not stored for a variable
There are 3 mechanisms

### 1 Missing Completely at Random, MCAR:
Missing completely at random (MCAR) is a type of missing data mechanism in which the probability of a value being missing is unrelated to both the observed data and the missing data. In other words, if the data is MCAR, the missing values are randomly distributed throughout the dataset, and there is no systematic reason for why they are missing.

For example, in a survey about the prevalence of a certain disease, the missing data might be MCAR if the survey participants with missing values for certain questions were selected randomly and their missing responses are not related to their disease status or any other variables measured in the survey.

### 2. Missing at Random MAR:
Missing at Random (MAR) is a type of missing data mechanism in which the probability of a value being missing depends only on the observed data, but not on the missing data itself. In other words, if the data is MAR, the missing values are systematically related to the observed data, but not to the missing data.
Here are a few examples of missing at random:

Income data: Suppose you are collecting income data from a group of people, but some participants choose not to report their income. If the decision to report or not report income is related to the participant's age or gender, but not to their income level, then the data is missing at random.

Medical data: Suppose you are collecting medical data on patients, including their blood pressure, but some patients do not report their blood pressure. If the patients who do not report their blood pressure are more likely to be younger or have healthier lifestyles, but the missingness is not related to their actual blood pressure values, then the data is missing at random.

## 3. Missing data not at random (MNAR)
It is a type of missing data mechanism where the probability of missing values depends on the value of the missing data itself. In other words, if the data is MNAR, the missingness is not random and is dependent on unobserved or unmeasured factors that are associated with the missing values.

For example, suppose you are collecting data on the income and job satisfaction of employees in a company. If employees who are less satisfied with their jobs are more likely to refuse to report their income, then the data is not missing at random. In this case, the missingness is dependent on job satisfaction, which is not directly observed or measured.
"""

import seaborn as sns

df=sns.load_dataset('titanic')

df.head()

## check missing values in dataset
df.isnull().sum()

sns.heatmap(df.isnull())

## HAndling missing by deleting rows

df.head()

## rowwise deletion
df.dropna().shape

df.shape

## Handling missing values by deleting columns

df.dropna(axis=1)

"""## Imputation Technqiues
### 1-Mean Value Imputation
"""

sns.distplot(df['age'])

df.age.isnull().sum()

df['Age_mean']=df['age'].fillna(df['age'].mean())

df[['Age_mean','age']]

## This tecnqiue work well when your data is normally distributed

"""### 2- Median Value Imputation
If you have ooutliers in dataset use thi technique
"""

df['Age_median']=df['age'].fillna(df['age'].median())

df[['Age_median','Age_mean','age']]

"""### 3- Mode Value Imputation-- Categorical"""

df[df['embarked'].isnull()]

df['embarked'].unique()

df[df['age'].notna()]['embarked'].mode()[0]

mode=df[df['age'].notna()]['embarked'].mode()[0]

mode

df['embarked_mode']=df['embarked'].fillna(mode)

df[['embarked_mode','embarked']]

df['embarked_mode'].isnull().sum()

df['embarked'].isnull().sum()

