# -*- coding: utf-8 -*-
"""5.0- Handling Outliers.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1keMOMQ9RTl2tt7om8IqtQANvn6FGJ0iB

## Handling Outliers

## 5 number Summary
1. Minimum Value
2. Q1- 25 percentile
3. Median
4. Q3- 75 percentile
5. MAximum
"""

import numpy as np
lst_marks=[45,32,56,75,89,54,32,89,90,87,67,54,45,98,99,67,74,1000,1100]

## [Lower Fence<---> Higher Fence]
Q1=np.percentile(lst_marks,[25])
print(Q1)

minimum,Q1,Q2,Q3,maximum=np.quantile(lst_marks,[0,0.25,0.50,0.75,1.0])

maximum

IQR=Q3-Q1
print(IQR)

lower_fence=Q1-1.5*(IQR)
higher_fence=Q3+1.5*(IQR)

lower_fence,higher_fence

outliers=[]
for i in lst_marks:
    if i>=0.75 and i<=142.75:
        print("This element is not an outlier")
    else:
        outliers.append(i)

outliers

import seaborn as sns

sns.boxplot(lst_marks)

lst_marks=[45,32,56,75,89,54,32,89,90,87,67,54,45,98,99,67,74]

sns.boxplot(lst_marks)

